"""Create tables with relationships

Revision ID: 576947c96575
Revises: a7464da8b8f5
Create Date: 2025-09-17 13:35:10.126461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576947c96575'
down_revision = 'a7464da8b8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_speakers', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_speakers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
