"""Create tables with relationships

Revision ID: a7464da8b8f5
Revises: be078d5c4103
Create Date: 2025-09-17 13:31:21.345675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7464da8b8f5'
down_revision = 'be078d5c4103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_speakers_session_id_sessions')),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_session_speakers_speaker_id_speakers')),
    sa.PrimaryKeyConstraint('id', 'session_id', 'speaker_id')
    )
    with op.batch_alter_table('bios', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_bios_speaker_id_speakers'), 'speakers', ['speaker_id'], ['id'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_sessions_event_id_events'), 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sessions_event_id_events'), type_='foreignkey')

    with op.batch_alter_table('bios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bios_speaker_id_speakers'), type_='foreignkey')

    op.drop_table('session_speakers')
    # ### end Alembic commands ###
